### ISSUE TITLE
FXレートの取得不具合

### ISSUE THREAD

**Issue by RunqRun** [TEAMNekozouneko/TheMining#1]
> 不具合

FXレートがAPIから取得できない

> 現状

API側は正常、リクエストの成功は確認済み

> 参考材料

コンソールのエラーログ (下の方に記載)

`[22:11:25] [Server thread/WARN]: Unexpected token END OF FILE at position 0.
[22:11:25] [Server thread/WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
[22:11:25] [Server thread/WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
[22:11:25] [Server thread/WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[22:11:25] [Server thread/WARN]:        at skript-json-1.1.1.jar//com.btk5h.skriptjson.skript.EffJSONToVariable.execute(EffJSONToVariable.java:71)
[22:11:25] [Server thread/WARN]:        at Skript (3).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[22:11:25] [Server thread/WARN]:        at Skript (3).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[22:11:25] [Server thread/WARN]:        at Skript (3).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[22:11:25] [Server thread/WARN]:        at reqn-1.2.3.jar//com.btk5h.reqn.skript.EffRequest.lambda$null$1(EffRequest.java:112)
[22:11:25] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[22:11:25] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[22:11:25] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1497)
[22:11:25] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[22:11:25] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[22:11:25] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[22:11:25] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[22:11:25] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by allie-developments** [comment]
APIサーバーは何で動いてますか

**Comment by RunqRun** [comment]
APIはNGINXで動いてます。
NGINX上にPHPを動かして、データの加工などしてJSONで返却してます。

**Comment by RunqRun** [comment]
修正いたしました。
グローバル変数に保存していたAPIのアクセスに必須のToken情報が破損していたようです。
Tokenを再設定したら直りました。

**Comment by RunqRun** [comment]
修正いたしました。
グローバル変数に保存していたAPIのアクセスに必須のToken情報が破損していたようです。
Tokenを再設定したら直りました。

**Comment by allie-developments** [comment]
ありがとうございます。
